apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: testapp-promo-process
  namespace: testapp
spec:
  vars:
    - name: gitopsRepo
      value: https://github.com/gjhenrique-prezi/kargo-test.git
    - name: imageRepo
      value: ghcr.io/gjhenrique-prezi/kargo-test
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitopsRepo }}
        checkout:
          - branch: master
            path: ./src
          - branch: stage/${{ ctx.stage }}
            create: true
            path: ./out
    - uses: git-clear
      config:
        path: ./out
    - uses: kustomize-set-image
      as: update
      config:
        path: ./src/apps/testapp/base
        images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
    - uses: kustomize-build
      config:
        path: ./src/apps/testapp/stages/${{ ctx.stage }}
        outPath: ./out
    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: ${{ task.outputs.update.commitMessage }}
    - uses: git-push
      config:
        path: ./out
    - uses: argocd-update
      config:
        apps:
          - name: testapp-${{ ctx.stage }}
            sources:
              - repoURL: ${{ vars.gitopsRepo }}
                desiredRevision: ${{ task.outputs.commit.commit }}
