apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: testapp
  namespace: testapp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/gjhenrique-prezi/kargo-test
        discoveryLimit: 5
